# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('political_party', models.CharField(blank=True, max_length=255)),
                ('approval_rating', models.IntegerField(default=50)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.FileField(upload_to='politicians')),
                ('website', models.CharField(blank=True, max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('mailing_address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('question', models.TextField()),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('not_specified', 'Not Specified')], default='not_specified', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PublicOfficeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.SlugField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('office_type', models.CharField(choices=[(b'federal', b'federal'), (b'state', b'state')], default=b'federal', max_length=64)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gogovgo_site.GovernmentDepartment')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ReasonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(blank=True, max_length=255, unique=True)),
                ('weight', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sentiment', models.CharField(choices=[(b'positive', b'positive'), (b'negative', b'negative'), (b'neutral', b'neutral')], default=b'neutral', max_length=64)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')], default='CA', max_length=120)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('body', models.TextField(null=True)),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'approved', b'approved')], default=b'pending', max_length=32)),
                ('nlp_sentiment', models.CharField(choices=[(b'positive', b'positive'), (b'negative', b'negative'), (b'neutral', b'neutral')], default=b'neutral', max_length=64)),
                ('politician', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gogovgo_site.Politician')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHasReasonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reason_tag', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='gogovgo_site.ReasonTag')),
                ('review', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='gogovgo_site.Review')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(b'male', b'male'), (b'female', b'female'), (b'unknown', b'unknown')], default=b'unknown', max_length=16)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(through='gogovgo_site.ReviewHasReasonTag', to='gogovgo_site.ReasonTag'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='politician',
            name='public_office_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gogovgo_site.PublicOfficeTitle'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='gogovgo_site.Politician'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogovgo_site.Politician'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'politician')]),
        ),
    ]
