# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 04:50
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0002_auto_20170822_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
