# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0003_auto_20170822_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
