# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 01:08
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0004_politician_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='hero_banner',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='hero_banner'),
        ),
    ]
