# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 02:52
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0005_politician_hero_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasontag',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterModelOptions(
            name='reviewhasreasontag',
            options={'verbose_name': 'Review has Tag'},
        ),
        migrations.AddField(
            model_name='review',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='gogovgo_site.Politician'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='hero_banner',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='hero_banner'),
        ),
    ]
