# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0006_auto_20171210_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontag',
            name='sentiment',
            field=models.CharField(choices=[(b'positive', b'positive'), (b'negative', b'negative'), (b'neutral', b'neutral')], default=b'neutral', max_length=64),
        ),
    ]
