# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0008_auto_20180129_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=1)),
                ('sentiment', models.CharField(choices=[(b'positive', b'positive'), (b'negative', b'negative'), (b'neutral', b'neutral')], default=b'neutral', max_length=64)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogovgo_site.Politician')),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.RemoveField(
            model_name='reviewhasreasontag',
            name='reason_tag',
        ),
        migrations.RemoveField(
            model_name='reviewhasreasontag',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ReasonTag',
        ),
        migrations.DeleteModel(
            name='ReviewHasReasonTag',
        ),
    ]
