# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0011_tag_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedReview',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gogovgo_site.Review')),
                ('counter', models.PositiveSmallIntegerField(default=1)),
                ('is_safe', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-counter'],
            },
        ),
    ]
