# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0013_auto_20180517_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2, null=True)),
                ('weight', models.IntegerField(default=1)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogovgo_site.Tag')),
            ],
        ),
    ]
